### ISSUE TITLE
Name clash with Redox OS

### ISSUE THREAD

**Issue by HeroesGrave** [PistonDevelopers/redox#23]
(For those who haven't seen it on /r/rust, http://www.redox-os.org/news/this-week-in-redox-1/)

A name change is probably needed to avoid confusion.

**Comment by bvssvni** [comment]
Good we didn't set up a domain yet.

Name suggestions?

**Comment by bvssvni** [comment]
- Redevs
- Rudox

**Comment by Haggus** [comment]
Alloy?
Although I have a feeling I've heard that before.

**Comment by bvssvni** [comment]
Alloy is already taken on crates.io https://crates.io/crates/alloy.

**Comment by bvssvni** [comment]
What about [Pluton](https://en.wikipedia.org/wiki/Pluton)?

**Comment by bvssvni** [comment]
Other suggestions from IRC:

- Gladiato
- Competito

**Comment by bvssvni** [comment]
I got the idea of Pluto from reading [list of alloys](https://en.wikipedia.org/wiki/List_of_alloys#Alloys_of_plutonium) and found alloys plutonium. Then I thought of Pluto, which has been photographed close up for the first time this year. Checked crates.io and nobody had reserved it. The .rs domene is also available.

**Comment by Haggus** [comment]
I like Pluto. It's short and easy to remember.

I was thinking about "Oxidation", since it is pretty much a different name for "rust".

**Comment by bvssvni** [comment]
Ok, we'll use Pluto then.
